name: Cross-Platform Tests

on:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ubuntu_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
    - run: java -version
    - run: mvn test # Reemplaza esto con tu comando de prueba para Ubuntu

  windows_test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
    - run: java -version
    - run: mvn test # Reemplaza esto con tu comando de prueba para Windows

  macos_test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
    - run: java -version
    - run: mvn test # Reemplaza esto con tu comando de prueba para macOS
